<?php
/*
 *
  * Copyright © 2025 MoneyHash. All rights reserved.
  *
  * Developed by: Ahmed Allam
  * Contact: mageserv.ltd@gmail.com (+20 102 0763062)
  *
  * Project: MoneyHash Payment Integration Extension for Magento 2
  *
  * NOTICE OF LICENSE
  * This source file is subject to the proprietary license that is bundled
  * with this package in the file LICENSE.txt. It is also available through
  * the world-wide-web at:
  * https://moneyhash.io/


 */

/**
 * @var \MoneyHash\SDK\Block\Info\MoneyHashPayment $block
 */
$str_pay_data = $block->getMoneyhashPayData("moneyhash_pay_data");
$pay_data = json_decode($str_pay_data, true);
?>
<strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong>

<dl>
  <dt>Selected Method:</dt>
  <dd><?= $block->escapeHtml($pay_data['selectedMethod'] ?? '') ?></dd>
</dl>
